"""empty message

Revision ID: 06cae3194cc4
Revises: fd8d05dad168
Create Date: 2023-01-23 00:23:47.939285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06cae3194cc4'
down_revision = 'fd8d05dad168'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('diary', 'created_at')
    # ### end Alembic commands ###
