"""empty message

Revision ID: 2ccf62a93c8e
Revises: a0b303eeb9e1
Create Date: 2023-01-31 08:05:20.580643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccf62a93c8e'
down_revision = 'a0b303eeb9e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('diary_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'diary', ['diary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'diary_id')
    # ### end Alembic commands ###
