"""empty message

Revision ID: 5b5d1e5c25d6
Revises: 06cae3194cc4
Create Date: 2023-01-23 00:24:44.924071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5d1e5c25d6'
down_revision = '06cae3194cc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
