"""empty message

Revision ID: 61ffc682ad16
Revises: 5b5d1e5c25d6
Create Date: 2023-01-23 00:25:55.260241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ffc682ad16'
down_revision = '5b5d1e5c25d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
