"""empty message

Revision ID: 9a465ccb1506
Revises: b1b3773720ab
Create Date: 2023-02-01 23:44:57.958710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a465ccb1506'
down_revision = 'b1b3773720ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_user_ibfk_1', 'book_user', type_='foreignkey')
    op.create_foreign_key(None, 'book_user', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_user', type_='foreignkey')
    op.create_foreign_key('book_user_ibfk_1', 'book_user', 'user', ['book_id'], ['id'])
    # ### end Alembic commands ###
