"""empty message

Revision ID: ad429a91f1f4
Revises: 595796cc0bb4
Create Date: 2023-02-01 07:39:05.641388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad429a91f1f4'
down_revision = '595796cc0bb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'diary_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('diary_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'diary', ['diary_id'], ['id'])
    # ### end Alembic commands ###
