"""empty message

Revision ID: ea0beee403e3
Revises: 9a465ccb1506
Create Date: 2023-02-01 23:47:04.345896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea0beee403e3'
down_revision = '9a465ccb1506'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_ibfk_1', 'book', type_='foreignkey')
    op.drop_column('book', 'contributer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('contributer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('book_ibfk_1', 'book', 'user', ['contributer_id'], ['id'])
    # ### end Alembic commands ###
